### ISSUE TITLE
Tab-completion

### ISSUE THREAD

**Issue by nickavv** [daikon-games/rt-shell#1]
It would be incredibly useful if rt-shell could support tab-completion. Would need a way to find assets by an incomplete name, or to somehow build a ds_map of all global scripts that start with `scr_` somehow.

**Comment by FaultyFunctions** [comment]
This would be very nice to have. Maybe a drop-down list to show all the functions that match too?

**Comment by nickavv** [comment]
As Faulty pointed out to me in a DM, the asset tagging system introduced in 2.3 could be helpful here.
Specifically the method [tag_get_assets](https://manual.yoyogames.com/index.htm#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FAssets_And_Tags%2Ftag_get_assets.htm) which returns a list of asset names that match a given tag.
If we could find a way to tag all of the user-created scripts, this would give us a nice list that we could filter based on the user's current input string.

Unfortunately as far as I can tell you can only apply a tag to a single asset (rather than a bunch of functions inside one script "asset"). Maybe this is inaccurate, or maybe this will change in a future release of GameMaker

**Comment by FaultyFunctions** [comment]
I have cracked the GML code. We don't need to use `tag_get_assets`. You can use `variable_instance_get_names(global)` to get all the global variables in the game which includes functions defined in global scope i.e. regular functions. Here is some code to grab the `sh_` prefixed functions and put them inside their own array in the Shell object's create event:

```javascript
var _global_variables = variable_instance_get_names(global);
shell_functions = [];
for (var i = 0; i < array_length(_global_variables); i++) {
	if (string_pos("sh_", string_lower(_global_variables[i])) == 1) { // if starts with "sh_"
		// Remove "sh_" prefix before adding to array
		shell_functions[array_length(shell_functions)] = string_delete(_global_variables[i], 1, 3);
	}
}
```

and now you have `shell_functions` array to do check against for autocompletion suggestions and tab completion!
