### ISSUE TITLE
[Discussion] Allow using functions that return an array within the suggestions meta-data for updates to suggestions during runtime

### ISSUE THREAD

**Issue by FaultyFunctions** [daikon-games/rt-shell#18]
What do we think about accepting functions within the suggestions array in meta_ functions? A potential use case for this would be to populate the suggestions with all the instances in the room. The functions could look like:

```gml
function sh_get_instance_count(args) {
  instance_number(args[1]);
}
```

```gml
function meta_get_instance_count() {
  return {
    arguments: ["object_index"],
    suggestions: [
      function() {
        var _objectArray = [];
        // loop to get all object names and push them to our array (probably discounting duplicates)
        return _objectArray;
      }
    ],
}
```

Then we would just use `if (is_array(data.suggestions[index])` to tell if we need to execute it or not.

Maybe this is a bad example, or this is getting too complex? I think it could be pretty useful though. Let me know your thoughts!

**Comment by nickavv** [comment]
Merged #34, so we will now support functions as argument suggesters in next release
