### ISSUE TITLE
try/catch support

### ISSUE THREAD

**Issue by Reverend-Greg** [daikon-games/rt-shell#19]
New to github, hope this is the proper way to do this:

**in obj_shell step event:**

**problem**:	If the console user makes a mistake with the arguments the program might crash.
**fix**:		Instead of forcing the coder to fool proof every sh_-function, wrap the script execution in the step event in a try-catch telling the console user to read the error in the GMS console.

		} else if (keyboard_check_pressed(vk_enter)) {
			if (isAutocompleteOpen) {
				self.confirmCurrentSuggestion();
			} else {
				var args = self.string_split(consoleString, " ");
				if (array_length(args) > 0) {
					var script = variable_global_get("sh_" + args[0]);
					if (script != undefined) {
						
					//***bug: INSTEAD OF THIS:
					//var response = script_execute(asset_get_index(script_get_name(script)), args);
					//***bugfix: USE THIS: 
					var response;
					try {
						response = script_execute(asset_get_index(script_get_name(script)), args);
					} catch (_exception) {
						show_debug_message("---ERROR---------------------------------");
						show_debug_message(_exception.message);
						show_debug_message(_exception.longMessage);
						show_debug_message(_exception.script);
						show_debug_message(_exception.stacktrace); 
						show_debug_message("-----------------------------------------");
						response = "ERROR within script: See GMS debug console for details";
					}
					//*** END bugfix -----------------------------------
						
						array_push(history, consoleString);

**Comment by nickavv** [comment]
Yep, that's a great suggestion and something I'd been thinking about implementing

**Comment by nickavv** [comment]
This will ship in the upcoming rt-shell 3.0.0 release. Thanks again!
