### ISSUE TITLE
console font issues

### ISSUE THREAD

**Issue by Reverend-Greg** [daikon-games/rt-shell#20]
**in obj_shell Draw GUI event (top)**:

**problem**:	The consoles autocomplete might not use the console font
**fix**:		If the console is open, always use the console font - even before 
			setting the surface due to the string_height() function.

		if (isOpen) {
			draw_set_font(consoleFont);//*** <------- bugfix: add this line
			if (!surface_exists(shellSurface)) {
				shellSurface = surface_create(display_get_gui_width(), display_get_gui_height());
				recalculate_shell_properties();
			} else if (surface_get_width(shellSurface) != display_get_gui_width() or surface_get_height(shellSurface) != display_get_gui_height()) {
				surface_resize(shellSurface, display_get_gui_width(), display_get_gui_height());
			}
	
			var lineHeight = string_height(prompt);
			var lineWidth = string_width(prompt);
	
			var textXOffset = 10 + anchorMargin;
	
**obj_shell Draw GUI event (bottom):**

**problem**:	When testing I'm often using the standard font to write something
			on screen. rt_shell doesn't reset the font to standard font though
			which means other areas where I use the standard font now use the 
			console font instead.
**fix**:		Reset the font at the end of the draw gui event about where the
			surface gets drawn.

				draw_set_color(c_white);
				draw_set_alpha(1);
			surface_reset_target();
	
			draw_set_font(-1); //*** <------- bugfix: add this line
			draw_surface(shellSurface, 0, 0);
		}

**Comment by FaultyFunctions** [comment]
Good catches! The first one is already fixed I believe. Although another fix related to that is in #17 so stay tuned for that to be merged. Should probably be tomorrow.

Your second fix, I will add to the PR and should be a part of the rest of the updates. Thanks!

**Comment by nickavv** [comment]
Both things should be fixed now, thanks for the report
