### ISSUE TITLE
Help for get_bgspeed messes up scrolling

### ISSUE THREAD

**Issue by nickavv** [daikon-games/rt-shell#21]
I haven't quite figured this one out yet but running
```
help get_bgspeed
```
breaks the scrolling, ending up with the prompt off the bottom of the scrollable area. No other command seems to cause this breakage, including ones with linebreaks and text wrapping in the output.

Definitely need to understand the nature of the failure and fix it, not to mention make sure an end-user would never get into that situation.

**Comment by FaultyFunctions** [comment]
I'm still working through this but it seems that when the output line is a specific length within two characters, this bug gets triggered and that function name along with the help description was the perfect length.

**Comment by nickavv** [comment]
Good research, pretty lucky we had a test case that happened to fall in
that range!
