### ISSUE TITLE
Value Out of Range error

### ISSUE THREAD

**Issue by SaySayTakamura** [daikon-games/rt-shell#33]
Hello, sorry for bothering but i started to use rt-shell those days but don't know why it doesn't work well with constructor.

I have a simple constructor that imports from JSON and displays the info on the scree or debug console.

`Item(_type, num)`

Ok, problem is, when running the normal way (give_item "healing" 0) it returns the error `"ds_list_find_value argument 1 incorrect type (undefined) expecting number (YYGI32)"` and doing the alternative way (give_item "healing",0) it returns `"Push :: Execution Error - Variable Index [2] out of range [2] - - 15.argument0(91,2) at gml_Script_sh_give_item(line 20) -  var _value2 = args[2]"`

This is already alternate method from what i had in mind.

```
function sh_give_item(args){

var _value1 = args[1]

var _value2 = args[2]

global.store[#0, 0]  = new Item(_value1, _value2)

return global.store[#0, 0].iname

}
```

Of course i tried to use direct link (instead of declaring variables and assigning them to the ARGS var) but that was my first idea and it didn't worked.

Any ideas of what am i doing wrong?

Note[1] = iname inherits from the constructor, it works normally without the console.

Note[2] = Great work the creator did with this console very well done and customizable.

Great work and sorry for bothering you.

**Comment by nickavv** [comment]
I think what the problem here is, is that the arguments that come in from `args` are all strings (the strings you typed in on the console).
So if your constructor expects `_value2` to be numeric, you should change that line to look like this:

```
var _value2 = real(args[2]);
```

Let me know if this fixes things for you

**Comment by SaySayTakamura** [comment]
Thanks for the answer Mr.Nick, i tried your method but still it gives the same errors.

Even when specifying the arguments(_value1 = string(args[1] and your method of _value2 = real(args[2])) it still gives the error tried the same methods i said on the start (give_item "healing" 0 and give_item "healing,0)

**Comment by nickavv** [comment]
I think you also may need to drop the quotation marks around `"healing"` in your command (and no commas needed either).
Let me know if that works, and if not can you please show me the constructor for `Item`?

**Comment by SaySayTakamura** [comment]
> I think you also may need to drop the quotation marks around `"healing"` in your command (and no commas needed either).
> Let me know if that works, and if not can you please show me the constructor for `Item`?

I forgot i was already converting whatever args[1] was to string and still was putting the quotation marks.

Thanks a ton for helping with this man, will keep this in mind when creating my future commands.

Again sorry for bothering you with such a silly problem.

Have a great rest of day and an awesome week for you.

**Comment by nickavv** [comment]
Don't worry about it at all, that's what I'm here for. Glad it's working now! You have a great day/week as well
