### ISSUE TITLE
Allow user to provide an autocomplete argument list.

### ISSUE THREAD

**Issue by FaultyFunctions** [daikon-games/rt-shell#7]
For example I have a shell command:

```gml
function sh_player_set_state(args) {
	_check_player_exists_shell();
	
	if (variable_struct_exists(obj_player.state_machine.states, args[1])) {
		obj_player.state_machine.set_state(args[1]);
		return "Set player state to: " + args[1];
	} else {
		return "State " + args[1] + " does not exist within the player.";
	}
}
```

It would be cool to provide a list of strings that `args[1]` could be and have that autocomplete as I type. I could type `> player_set_state f` and it could give me options for `fall` or `fire`. I don't know how this would be implemented exactly and what the best way would be to provide this information to the shell object but this is just an idea. Let me know what you think!

**Comment by nickavv** [comment]
Yeah, I'd love to be able to do this, and/or give the arguments themselves names so we can show hints, like if I have a method called `spawn` that takes `objectName` `x` and `y` as its arguments then I would be able to see `spawn objectName x y` after typing in `spawn`, maybe?

But yeah in general getting the information to obj_shell is the tricky part, we have to run some code either at start-up or just-in-time, and finding a clean solution that's easy for end-users to implement is an interesting challenge.

**Comment by FaultyFunctions** [comment]
Okay now that we have autocomplete functionality in the horizon I think we can talk about this more directly. What do you think of having a function you can call after defining your original shell function to add arguments to an function info struct in the shell object? Here is an example:

```gml
/// Scripts
function sh_spawn_cheese(args) {
    var _cheese = instance_create_layer(0, 0, "Cheese_Layer", obj_cheese);
    _cheese.type = args[1];
}
obj_shell.add_autocomplete("spawn_cheese", 0, ["cheddar", "swiss", "pepperjack", "feta"]);

/// Pseudo Implementation in obj_shell
function add_autocomplete(function_name, argument_number, autocomplete_array) {
    // Store autocomplete array inside autocomplete functions struct for use later
    array_push(autocompleteFunctions[$ function_name][argument_number], autocomplete_array);
}
```

Not sure if there are any other viable solutions? What do you think? We could define argument hints in a similar way and figure out how to display this via UI as well.

**Comment by nickavv** [comment]
That's not going to work, because at the time you're defining shell functions (in a script resource) there is no instance of `obj_shell` to work with.

What I've been thinking would be that we have users define _another_ function, with a different prefix, and then call that function from our shell instance once we have one. For instance:

```
/// DEFINING MY SHELL FUNCTION
function sh_spawn_cheese(args) {
    var _cheese = instance_create_layer(0, 0, "Cheese_Layer", obj_cheese);
    _cheese.type = args[1];
}
/// Defining manual function
function man_spawn_cheese() {
   return {
      arguments: ["cheese_type"],
      argument_suggestions: [
         ["cheddar", "swiss", "pepperjack", "feta"]
      ]
   };
}
```
Then inside our shell object we can pick up all the `man_` functions the same way we find the `sh_` ones, and copy the data structures we get from running those into instance's memory.

**Comment by FaultyFunctions** [comment]
Ah yeah I didn't think about the object not existing. Defining another function would be a fine solution.

What do you think about moving rt-shell away from the object dependency and transferring it to scripts? So instead of adding an object to your project you are adding some script files and the shell data would be initialized on game load, and the user would be able to choose which of their objects update the shell with `rt_shell_tick()` in the step event.

I am basing this off of how a lot of JujuAdam's libraries function. Check out: https://github.com/JujuAdams/Input

This would require some rewriting of things but I'm willing to try to tackle it. Let me know what you think.

**Comment by nickavv** [comment]
I'm against that concept personally. GameMaker is based around objects and I prefer libraries that try to integrate into their environment nicely rather than trying to work around it

**Comment by FaultyFunctions** [comment]
I would've agreed with you pre-2.3 but alas, either way works. I'll throw some stuff together for this and see what happens!

**Comment by nickavv** [comment]
Thanks @FaultyFunctions !
